<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class RateCalculationRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     **** hypothesis : minimum of 0.01 for each field
     * @return array
     */
    public function rules(): array
    {
        return [
            'rate' => 'required|array',
            'rate.energy' => 'required',
            'rate.time' => 'required',
            'rate.transaction' => 'required',
            'cdr' => 'required|array',
            'cdr.meterStart' => 'required|numeric',
            'cdr.meterStop' => 'required|numeric',
            'cdr.timestampStart' => 'required|date_format:Y-m-d\TH:i:s\Z',
            'cdr.timestampStop' => 'required|date_format:Y-m-d\TH:i:s\Z',
        ];
    }

    /**
     * There could be better validation messages if needed
     * @return array
     */
    public function messages(): array
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
